HW1_nh2706
================

# Section 1

## Loading Data

Downloading the a package containing the `penguins` dataset

``` r
data("penguins", package = "palmerpenguins")
```

## Data Summary

Presenting the data to you:

``` r
skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim_variable | n_missing | complete_rate | ordered | n_unique | top_counts                  |
|:--------------|----------:|--------------:|:--------|---------:|:----------------------------|
| species       |         0 |          1.00 | FALSE   |        3 | Ade: 152, Gen: 124, Chi: 68 |
| island        |         0 |          1.00 | FALSE   |        3 | Bis: 168, Dre: 124, Tor: 52 |
| sex           |        11 |          0.97 | FALSE   |        2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim_variable     | n_missing | complete_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:------------------|----------:|--------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill_length_mm    |         2 |          0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill_depth_mm     |         2 |          0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper_length_mm |         2 |          0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body_mass_g       |         2 |          0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year              |         0 |          1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

The summary above shows that the size of the dataset is 344 rows long
and 8 columns wide.

The mean flipper length within the dataset is 200.92 millimeters.

## Scatterplot with bill_length and flipper_length

Creating a scatterplot of `bill_length_mm` and `flipper_length_mm`,
using the different species to colorcode the individual points.

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color=species)) + geom_point()
```

![](p9105_hw1_nh2706_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

Subsequently, exporting the scatterplot to the project directory as a
**PDF**

``` r
ggsave("scatterplot.pdf")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

# Section 2

## Data Frame Creation

Using `tible`, we are now creating a datafram with the following specs:

-   **random_vec** = random sample of size 10 from a standard Normal
    distribution
-   **logical_vec** = logical vector indicating whether elements of the
    sample are greater than 0
-   **character_vec** = character vector of length 10
-   **factor_vec** = factor vector of length 10, with 3 different factor
    “levels”

``` r
hw_frame=
  tibble(
    random_vec=rnorm(n=10),
    logical_vec=random_vec>0,
    character_vec= c(sample(LETTERS, 10, replace = TRUE)),
    factor_vec=factor(cut(random_vec,3,labels=c('Low','Medium','High')))
  )
```

## Calculating the mean of each variable

When trying to take the mean of each variable, the result is the
following (*rounded to the nearest tenth*):

-   **random_vec** = -0.44. This works, because it is a numeric
    variable.
-   **logical_vec** = 0.3. This works, because it is a TRUE/FALSE
    variable, which can be converted to numeric values (TRUE = 1 and
    FALSE = 0).
-   **character_vec** = No result because the variable is not numerical.
-   **factor_vec** = No result because the variable is not numerical.

## Converting character and factor variables to numeric variables

Given that the mean of the character and factor variables could not be
calculating, the next step is to convert those variables to a numeric
variable.

To do so, I am creating three new variables `Num_logical_vec`,
`Num_character_vec`, `Num_factor_vec`.

``` r
Num_logical_vec=as.numeric(hw_frame$logical_vec)
Num_character_vec=as.numeric(hw_frame$character_vec)
Num_factor_vec=as.numeric(hw_frame$factor_vec)
```

The result of this is that the logical and factor variable can be
converted to a numeric variable based on logic (TRUE/FALSE & 3
Categories). However, the character variable is filled with NA, since
there is no logic to convert to numeric values.

# END OF HW1
